### ISSUE TITLE
add priority for todo item by html select tag

### ISSUE THREAD

**Issue by alexhe** [JoselynDRF/react-redux-typescript-todolist#2]
```typescript

  const submitHandler = (e: FormEvent) => {
    e.preventDefault();

    if (inputText && inputText.current && inputText.current.value !== '') {
      addItem(priority, inputText.current.value);
      inputText.current.value = '';
    }
  };

//p1
  let priority: string = "middle";
  const onChangePriority = (e: React.ChangeEvent<HTMLSelectElement>) => {
      priority = e?.target.value;
      return;
  };


  return (
    <form onSubmit={submitHandler}>
//p2
    <select id="priority" onChange={onChangePriority}>
      <option value="low">low</option>
      <option value="middle" selected>middle</option>
      <option value="high">high</option>
    </select>


      <input ref={inputText} placeholder="What needs to be done?" />
      <button type="submit">
        <i className="fas fa-plus" />
      </button>
    </form>
  );
```

**Comment by alexhe** [comment]
TodoForm.tsx

**Comment by alexhe** [comment]
use react standard way:useState() to fix select default value warning :

```typescript


export default ({ emptyList, addItem }: TodoFormProps) => {
  //q1:
  const [state, setState] = useState({priority: "middle"});

  const inputText = useRef<HTMLInputElement>(null);
  const focusInputText = () => inputText?.current?.focus();

  useEffect(() => {
    if (emptyList) focusInputText();
  });

  const submitHandler = (e: FormEvent) => {
    e.preventDefault();

    if (inputText && inputText.current && inputText.current.value !== '') {
      addItem(state.priority, inputText.current.value);
      inputText.current.value = '';
    }
  };

  //q2
  const onChangePriority = (e: React.ChangeEvent<HTMLSelectElement>) => {
      setState({priority: e?.target.value});
      return;
  };


  return (
    <form onSubmit={submitHandler}>
    <select id="priority" value={state.priority} onChange={onChangePriority}>
      <option value="low">low</option>
      <option value="middle" >middle</option>
      <option value="high">high</option>
    </select>

      <input ref={inputText} placeholder="What needs to be done?" />
      <button type="submit">
        <i className="fas fa-plus" />
      </button>
    </form>
  );
};

```

**Comment by alexhe** [comment]
styles.scss: select option居中对齐， 同时解决chrome兼容性问题

```css

    form {
      display: flex;
      justify-content: space-between;
      width: 100%;
      background-color: $white-color;
  
      select {
        margin: 0 0.8rem;
        padding: 0 0.8rem;
        text-align: center;
        justify-content: center;
        text-align-last:center;

        option {
          text-align: center;
        }
      }
```
